Add csaf_validator
csaf-poc/csaf_distribution pull request #323
Opened 2023-01-29 18:34 UTC by s-l-teichmann

Add a `csaf_validator` tool.

Resolves #258

2023-01-30 07:01 UTC, tschmidtb51 requested changes
Please see my comments.

2023-01-30 07:01 UTC, tschmidtb51 commented on cmd/csaf_validator/main.go
> +		fmt.Printf("%q %s remote validation.\n", file, passes)
Please add an option to see the results of the remote validator (as one could use that to run optional or informative tests).

2023-01-30 13:13 UTC, s-l-teichmann commented on cmd/csaf_validator/main.go
> +		log.Println("No domains given.")
Resolved with 6a60e8d8ce839b4f4a58cc493569974f59bebe51

2023-01-30 13:14 UTC, s-l-teichmann commented on cmd/csaf_validator/main.go
> +		}
Resolved with 6a60e8d8ce839b4f4a58cc493569974f59bebe51

2023-01-30 13:14 UTC, s-l-teichmann commented on cmd/csaf_validator/main.go
> +			return fmt.Errorf("remote validation of %q failed: %w",
Resolved with 6a60e8d8ce839b4f4a58cc493569974f59bebe51

2023-01-30 13:15 UTC, s-l-teichmann commented on cmd/csaf_validator/main.go
> +		// Validate against remote validator.
Resolved with a8493c0dd28f8995a873c42b1f372aab29e56806

2023-01-30 13:21 UTC, s-l-teichmann commented on cmd/csaf_validator/main.go
> +		fmt.Printf("%q %s remote validation.\n", file, passes)
The [remote validation code](https://github.com/csaf-poc/csaf_distribution/blob/0c398199303a2bb0ddc76a5046933735789ef115/csaf/remotevalidation.go#L97) currently does not handle details of the validation.

To do so this code has to be extended.

2023-01-30 14:57 UTC, tschmidtb51 commented on cmd/csaf_validator/main.go
> +		fmt.Printf("%q %s remote validation.\n", file, passes)
@s-l-teichmann Thanks for the hint. We'll track that as new issue #324. If you think that it's in the threshold - feel free to do it in this PR.

2023-01-30 15:11 UTC, s-l-teichmann commented on cmd/csaf_validator/main.go
> +		fmt.Printf("%q %s remote validation.\n", file, passes)
I would prefer to tackle this in another PR. 

Adding this feature would involve changing the internal caching of the remote results which leads to
to the risk to break the library. Breaking the library could endanger
the other uses in the provider, the downloader, etc.

2023-01-30 16:53 UTC, tschmidtb51 commented on cmd/csaf_validator/main.go
> +		// Validate against remote validator.
Only partially resolved. Tracking as new issue #325. Using this version to get it merged.

2023-01-30 16:54 UTC, tschmidtb51 approved these changes
LGTM and works.

2023-01-30 16:55 UTC, tschmidtb51 commented
@bernhardreiter Ready for you to go ;-)

2023-01-31 10:16 UTC, bernhardreiter approved these changes
The validator itself looks fine. It is not yet distributed for windows, so splitting out #326 .

2023-01-31 10:30 UTC, merged