Remote validator output
csaf-poc/csaf_distribution pull request #347
Opened 2023-03-02 16:36 UTC by JanHoefelmeyer

Solves https://github.com/csaf-poc/csaf_distribution/issues/324 by adding the --verbose flag to the csaf_validator.

Calling the validator with the verbose flag but without a remote validator currently has no effect. (The validator behaves as if verbose was not called)

2023-03-02 19:38 UTC, tschmidtb51 requested changes
Some minor changes...

2023-03-02 19:38 UTC, tschmidtb51 commented on cmd/csaf_validator/main.go
> +	Verbose                bool     `long:"verbose" description:"If a remote validator was used, display the results in JSON format"`
In the other programs `-v` is additionally short for  `--verbose`

2023-03-02 19:38 UTC, tschmidtb51 commented on csaf/remotevalidation.go
> +}
The test name should be returned as well `name`. Otherwise, it is hard to figure out which test is which.
```suggestion
        Name    string    `json:"name"`
}

2023-03-02 19:56 UTC, tschmidtb51 commented on csaf/remotevalidation.go
> +}
Please also sort keys (errors, warning, infos) it to match https://github.com/csaf-poc/csaf_distribution/issues/324#issuecomment-1421665324

2023-03-02 19:59 UTC, tschmidtb51 commented
Given #348, I'm not 100% sure whether `--verbose` is the right keyword...

2023-03-03 06:44 UTC, JanHoefelmeyer commented on cmd/csaf_validator/main.go
> +	Verbose                bool     `long:"verbose" description:"If a remote validator was used, display the results in JSON format"`
Along with renaming verbose to output due to the concerns in https://github.com/csaf-poc/csaf_distribution/pull/347#issuecomment-1452470345, the -o flag has now been added

2023-03-03 06:45 UTC, JanHoefelmeyer commented on csaf/remotevalidation.go
> +}
Has now been done

2023-03-03 09:06 UTC, s-l-teichmann requested changes
There are many things I dont like about this.
@JanHoefelmeyer  we need to talk about this.
We should set this back to draft.

2023-03-03 09:30 UTC, tschmidtb51 commented on csaf/remotevalidation.go
> +}
Thanks for pointing that out - I didn't check the order in the comment. The order should match: https://github.com/csaf-poc/csaf_distribution/issues/348#issue-1607401382

2023-03-14 12:57 UTC, s-l-teichmann submitted a review, later dismissed
LGTM and works.

2023-03-14 14:11 UTC, s-l-teichmann approved these changes
Still LGTM and works.

2023-03-14 21:06 UTC, tschmidtb51 approved these changes
Comment on the Error message - other than that: LGTM

2023-03-15 00:33 UTC, s-l-teichmann commented on cmd/csaf_validator/main.go
> +					file, err)
As there where actually no errors raised on this code path I have removed the error handling in this spot completely. This also gets rid of the problem of having a better error message. ;-)

2023-03-15 00:37 UTC, s-l-teichmann approved these changes
LGTM

2023-03-15 07:51 UTC, tschmidtb51 approved these changes
LGTM

2023-03-15 10:02 UTC, merged