Lockfile aggregator
csaf-poc/csaf_distribution pull request #351
Opened 2023-03-20 07:41 UTC by JanHoefelmeyer

Adds option no_lock to csaf_aggregator. If set to true, no lockfile will be used. If no_lock is false, the configs lockfile will be used. If no lockfile is specified, /var/csaf_aggregator/run.lock will be used as default.

2023-03-24 18:32 UTC, tschmidtb51 reviewed
A few comments here:
1. As we change the default behavior, I guess it make sense to create the lock-file if it does not exist, correct?
2. I guess we should also improve the error message: "cannot lock to file /var/csaf_aggregator/run.lock" => "cannot acquire file lock at <PATH>. Maybe the CSAF aggregator is already running?"
3. I'm curious: Is there a specific reason why we choose /var/csaf_aggregator/run.lock for the lock file and not /var/lock/<something>?

2023-03-24 18:32 UTC, tschmidtb51 commented on cmd/csaf_aggregator/config.go
> +	defaultLockFile       = "/var/csaf_aggregator/run.lock"
I'm curious: Is there a specific reason why we choose `/var/csaf_aggregator/run.lock` for the lock file and not `/var/lock/<something>`?

2023-03-24 19:29 UTC, tschmidtb51 commented
Just discussed with @s-l-teichmann:
1. Yes. We should create it.
2. Please implement.
3. Use `/var/lock/csaf_aggregator.lock` or /var/lock/csaf_aggregator/lock`

2023-03-24 19:29 UTC, tschmidtb51 requested changes
Just discussed with @s-l-teichmann:
1. Yes. We should create it.
2. Please implement.
3. Use `/var/lock/csaf_aggregator.lock` or `/var/lock/csaf_aggregator/lock`

2023-03-27 11:05 UTC, s-l-teichmann commented
> Just discussed with @s-l-teichmann:
> 
>     1. Yes. We should create it.
> 
>     2. Please implement.
> 
>     3. Use `/var/lock/csaf_aggregator.lock` or `/var/lock/csaf_aggregator/lock`

to 1.

If I read the [sources](https://github.com/gofrs/flock/blob/6f010d1acea74a32f2f2066bfe324c08bbee30e3/flock.go#L128) of the library correctly, there is no need to create the file manually, as it
is already done by the library.

2023-03-27 11:22 UTC, s-l-teichmann approved these changes
LGTM

2023-03-27 21:22 UTC, tschmidtb51 approved these changes
LGTM and works

2023-03-28 05:24 UTC, merged