Rephrase csaf validation result
csaf-poc/csaf_distribution pull request #356
Opened 2023-03-27 11:10 UTC by JanHoefelmeyer

Give out a warning if no remote validator is configured.

Clarify that the inbuild validator only validates against the schema.

Solves https://github.com/csaf-poc/csaf_distribution/issues/338

2023-03-27 21:10 UTC, tschmidtb51 requested changes
Please see my comment.

2023-03-27 21:10 UTC, tschmidtb51 commented on cmd/csaf_checker/reporters.go
>  	} else {
I think we need to extend the logic here:
If a remote validator and one of the presets `basic`, `mandatory`, `extended` or `full` was used, we should say `"All advisories validated fine."`
If a remote validator and none of the presets `basic`, `mandatory`, `extended` or `full` was used or no remote validator was used, we should say `"All advisories validated fine against the schema."`

2023-03-30 08:53 UTC, s-l-teichmann approved these changes
LGTM

2023-03-30 16:46 UTC, tschmidtb51 approved these changes
LGTM and works

2023-03-30 17:09 UTC, merged