Role requirements 11-14 or 15-17
csaf-poc/csaf_distribution pull request #373
Opened 2023-06-15 13:13 UTC by s-l-teichmann

Solves #304

2023-06-15 13:15 UTC, JanHoefelmeyer submitted a review, later dismissed
LGTM & works

2023-06-16 09:59 UTC, tschmidtb51 reviewed
I hadn't had time to do a full root cause analysis. Here are some quick results from my tests.

2023-06-16 09:59 UTC, tschmidtb51 commented on cmd/csaf_checker/processor.go
> +			p.badROLIEFeed.error(
I guess, if there is no TLP label, it must be unlabeled, correct?

2023-06-16 09:59 UTC, tschmidtb51 commented on cmd/csaf_checker/roliecheck.go
> +		if hasSummary.Contains(label) && len(p.labelChecker.advisories[label]) > 0 {
The warning message gets triggered here - also if I check that against `sick.com` or another site, that has all their documents listed in a single ROLIE feed.

2023-06-16 12:13 UTC, JanHoefelmeyer commented on cmd/csaf_checker/processor.go
> +			p.badROLIEFeed.error(
Yes, that was also the idea. Missed that distribution is optional, https://github.com/csaf-poc/csaf_distribution/pull/373/commits/8d269ce106e963d4f4d790c2d9ab692b7ad99e8f amends this by only requiring document to be present. If document is present, it will then try to extract the TLP level and return unlabeled if it is unable to.

2023-06-19 14:59 UTC, tschmidtb51 requested changes
Rules 5-7 are missing for [CSAF providers](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#722-role-csaf-provider). Found by testing a "CSAF trusted provider" as cert-bund.de

2023-06-19 14:59 UTC, tschmidtb51 commented on cmd/csaf_checker/rules.go
> +			publisherRules,
Rules 5-7 are missing here

2023-06-23 09:10 UTC, JanHoefelmeyer approved these changes
LGTM and works

2023-06-23 09:42 UTC, JanHoefelmeyer submitted a review, later dismissed
LGTM & works

2023-06-24 22:15 UTC, tschmidtb51 reviewed
Minor comments -other than that: LGTM

2023-06-27 23:33 UTC, tschmidtb51 approved these changes
LGTM

2023-06-28 07:23 UTC, JanHoefelmeyer approved these changes
LGTM & works

2023-06-28 07:24 UTC, merged