Improve error message if filename does not match document/tracking/id and let it be reported by the proper reporter
csaf-poc/csaf_distribution pull request #382
Opened 2023-06-28 07:11 UTC by JanHoefelmeyer

Solves https://github.com/csaf-poc/csaf_distribution/issues/380

2023-06-28 18:12 UTC, tschmidtb51 approved these changes
LGTM and works

2023-06-28 18:20 UTC, tschmidtb51 requested changes
This might be unrelated (or fixed by #357) - but if I try this PR with an empty ROLIE feed. I get a memory access violation:

```
roliecheck.go:247
processor.go:977
processor.go:322
processor.go:243
main.go:151
main.go:174
```

Maybe something is not initialized yet?

2023-06-29 06:41 UTC, JanHoefelmeyer commented
> This might be unrelated (or fixed by #357) - but if I try this PR with an empty ROLIE feed. I get a memory access violation:
> 
> ```
> roliecheck.go:247
> processor.go:977
> processor.go:322
> processor.go:243
> main.go:151
> main.go:174
> ```
> 
> Maybe something is not initialized yet?

The branch seems to be based off of an older version (1 commit ahead, 41 behind main) which still has that error not yet fixed. The changes within this PR do not actually change anything that should be able to break something elsewhere.

They only rephrase an error message and use a different reporter. To be on the safe side, I merged main into this branch, which - on my side at least - fixes this error.

2023-06-30 04:55 UTC, tschmidtb51 commented on cmd/csaf_checker/processor.go
> +			p.badFilenames.error("%s: %v\n", u, err)
```suggestion
                        p.badFilenames.error("%s: %v", u, err)

2023-06-30 04:57 UTC, tschmidtb51 submitted a review, later dismissed
LGTM and works

2023-06-30 04:57 UTC, tschmidtb51 commented
@s-l-teichmann ready for review

2023-06-30 05:52 UTC, tschmidtb51 approved these changes
LGTM and works

2023-06-30 21:36 UTC, s-l-teichmann approved these changes
LGTM

2023-06-30 21:36 UTC, merged