Check for advisoryLabel instead of feedlabel
csaf-poc/csaf_distribution pull request #390
Opened 2023-07-05 11:35 UTC by JanHoefelmeyer

Currently the check on proper access-protectedness is done via checking the TLP-level of the feed. Any advisory placed within the wrong feed would potentially be missed or misdiagnosed.  This PR causes the check to check for the TLP-level of the advisory instead.

2023-07-05 13:38 UTC, ThomasJunk submitted a review, later dismissed
LGTM

2023-07-05 13:46 UTC, s-l-teichmann requested changes
It's more complicated. The open http client logic is affected as well.
I will re-work it.

2023-07-05 20:43 UTC, s-l-teichmann approved these changes
LGTM now.

2023-07-06 07:19 UTC, ThomasJunk approved these changes
OK!

2023-07-06 07:38 UTC, merged