Error to explaining warning when loading lpmd messages in checker
csaf-poc/csaf_distribution pull request #429
Opened 2023-08-17 08:54 UTC by JanHoefelmeyer

solves https://github.com/csaf-poc/csaf_distribution/issues/415

2023-08-17 13:38 UTC, s-l-teichmann requested changes

2023-08-17 13:38 UTC, s-l-teichmann commented on cmd/csaf_checker/processor.go
>  		// TODO: Filter depending on the role.
The TODO should be removed.

2023-08-18 07:23 UTC, JanHoefelmeyer commented on cmd/csaf_checker/processor.go
>  		// TODO: Filter depending on the role.
Done via https://github.com/csaf-poc/csaf_distribution/pull/429/commits/16041bdb897aa9208f2c438cb0a521e7d3337b53

2023-08-18 09:25 UTC, bernhardreiter approved these changes
LGTM

2023-08-18 09:29 UTC, s-l-teichmann approved these changes
LGTM & works

2023-08-18 09:29 UTC, merged