Fix missing
csaf-poc/csaf_distribution pull request #441
Opened 2023-08-23 10:41 UTC by JanHoefelmeyer

Part of https://github.com/csaf-poc/csaf_distribution/issues/438

Currently, any file discrepancies between the different file retrieval methods is reported in integrity.
This PR changes the checker so it reports any file missing from a list in their respective retrieval methods Requirement

2023-08-23 15:17 UTC, s-l-teichmann approved these changes
LGTM

2023-08-24 12:40 UTC, ThomasJunk commented
Code looks good, BUT

I have a problem while testing.

Using the example data from the [standard](https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#7113-requirement-13-changescsv)

```"2020/example_company_-_2020-yh4711.json","2020-07-01T10:09:07Z"```

results in 

```javascript
...
{
 "type": 2,
 "text": "Fetching https://127.0.0.1/.well-known/csaf/2020/example_company_-_2020-yh4711.json failed: Status code 404 (404 Not Found)"
},
...
```

But there seems to be no complaint that this isn't found in any ROLIE or some similar message (which should be according to @JanHoefelmeyer ).

More:

Using 

```"2019/rhsa-2019_1862.json","2020-07-01T10:09:07Z"```

results in

```javascript
{
              "type": 2,
              "text": "Fetching https://127.0.0.1/.well-known/csaf/2019/rhsa-2019_1862.json failed: Status code 404 (404 Not Found)"
            },
...
            {
              "type": 2,
              "text": "https://localhost:8443/.well-known/csaf/amber/2019/rhsa-2019_1862.json in ROLIE, not in changes.csv"
            },
            {
```

which seems to be confusing. Going one step further:

Using 

```"amber/2019/rhsa-2019_1862.json","2020-07-01T10:09:07Z"```

results in:

```javascript
            {
              "type": 2,
              "text": "https://localhost:8443/.well-known/csaf/amber/2019/rhsa-2019_1862.json in ROLIE, not in changes.csv"
            },

```

which is confusing. 

```"amber/2019/rhsa-2019_1862.json","2020-07-01T10:09:07Z"``` shouldn't be standard conform.
I expected it either to be found and the errormessage about it missing wouldn't appear or it would be listed as "not found" like with the example data.

Am I testing wrong here or is there a bug hidden?

2023-08-24 12:53 UTC, ThomasJunk commented
Okay using `URLs` seems to work. I _misread_ the standard saying:
> The file changes.csv MUST contain the filename 

which should read 

> The file changes.csv MUST contain URL pointing to the file.

2023-08-24 12:57 UTC, ThomasJunk commented
`/amber/2019/rhsa-2019_1862.json` would've worked.

2023-08-25 06:53 UTC, s-l-teichmann commented
Jan mentioned yesterday there is something wrong with this he still wants to fix. I currently do not know any more details. Postponing merge ATM.

2023-08-25 07:53 UTC, bernhardreiter requested changes
@JanHoefelmeyer please fix what you have planned to fix.

2023-08-26 10:31 UTC, s-l-teichmann commented
> (I have added a review so that merging is blocked until @JanHoefelmeyer can do his fixes next week.)

The "right" way to prevent this is to set it back to draft.

2023-09-04 10:45 UTC, JanHoefelmeyer commented
Opened https://github.com/csaf-poc/csaf_distribution/issues/451 and https://github.com/csaf-poc/csaf_distribution/issues/452 since the issues of the PR discussed here do not originate from these changes, nor are they part of https://github.com/csaf-poc/csaf_distribution/issues/438.

2023-09-04 12:34 UTC, s-l-teichmann approved these changes
Still LGTM

2023-09-19 11:02 UTC, ThomasJunk approved these changes
LGTM & Works

2023-09-19 13:52 UTC, merged