PMD: Support legacy security.txt location as fallback.
csaf-poc/csaf_distribution pull request #506
Opened 2023-11-12 09:19 UTC by s-l-teichmann

If we don't find the security.txt in the well-known folder try to find it under https://domain/security.txt as a fallback.

Solves #503

2023-11-13 08:33 UTC, JanHoefelmeyer requested changes
The checker still doesn't search for the Security.txt within the legacy location. This needs to be adjusted before merging.

2023-11-13 09:01 UTC, s-l-teichmann commented
> The checker still doesn't search for the Security.txt within the legacy location. This needs to be adjusted before merging.

Addressed with 0a2b69b

2023-11-14 06:57 UTC, JanHoefelmeyer approved these changes

2023-11-14 06:57 UTC, JanHoefelmeyer approved these changes
LGTM

2023-11-16 01:03 UTC, tschmidtb51 requested changes
Regarding the `csaf_checker`: The reporting seems to be sub-optimal: 
Requirement 7 reports a warning of an unexpected situation "fetching the .well-known/security.txt fails with 404"
Requirement 8 does report that  "fetching the .well-known/security.txt fails with 404" but does not state that the one under /security.txt was found.

Actions:
- We need to add at least under 8 that the /security.txt was found (and if it had a CSAF entry).
- We need to confirm that no security.txt (at all) does not result in an error (in requirement 7) if one of the other ways led to a PMD

2023-11-22 07:29 UTC, JanHoefelmeyer commented on cmd/csaf_checker/processor.go
> +		lmsg := folder + "security.txt:" + msg
As of [fb7c77b](https://github.com/csaf-poc/csaf_distribution/pull/506/commits/fb7c77b419099c8c215f1d0c432b6417b41dbcc4):

> We need to add at least under 8 that the /security.txt was found (and if it had a CSAF entry).

There are now separate messages for the .well-known security.txt and the legacy one. The legacy one still only will be checked if the .well-known one was faulty. Both messages start with their respective location to differentiate themselves.

> We need to confirm that no security.txt (at all) does not result in an error (in requirement 7) if one of the other ways led to a PMD

Problems while loading the PMD (as reported in your example) all result in a warning only, no matter what, and are only reported, as long as the PMD itself is valid, see https://github.com/csaf-poc/csaf_distribution/issues/415 and https://github.com/csaf-poc/csaf_distribution/pull/429

2023-11-23 05:45 UTC, JanHoefelmeyer approved these changes
LGTM

2023-11-28 08:21 UTC, tschmidtb51 approved these changes
LGTM and works

2023-11-30 06:34 UTC, merged