Lower required Go version to 1.20
csaf-poc/csaf_distribution pull request #509
Opened 2023-11-15 10:30 UTC by s-l-teichmann

This makes it easier to be used in other projects as a library.

2023-11-15 10:41 UTC, JanHoefelmeyer submitted a review, later dismissed
LGTM

2023-11-15 11:24 UTC, ThomasJunk approved these changes
LGTM

2023-11-15 17:45 UTC, tschmidtb51 commented
We also need to change the workflows to make sure that we are not accidentally using 1.21 functions...

2023-11-16 00:37 UTC, s-l-teichmann commented
> We also need to change the workflows to make sure that we are not accidentally using 1.21 functions...

@tschmidtb51 
No, we should _not_ do this. We should always use the latest stable to build our stuff. The `go.mod` file ensures that we don't use language features of a higher version. The binaries we deliver should benefit from the newer compilers.

2023-11-16 01:06 UTC, tschmidtb51 commented
> @tschmidtb51 No, we should _not_ do this. We should always use the latest stable to build our stuff. The `go.mod` file ensures that we don't use language features of a higher version. The binaries we deliver should benefit from the newer compilers.

@s-l-teichmann Thanks for the clarification.
Processwise: As I did the changes via the web, it might be easiest if you create a new PR with just the commits it originally had...

2023-11-16 01:22 UTC, tschmidtb51 requested changes
Did someone test that successfully?

I just tried to run in on a machine with Go 1.20.4 and got the following result:
```
make build_linux 
mkdir -p bin-linux-amd64/ 
env GOARCH=amd64 GOOS=linux go build -o bin-linux-amd64/  -ldflags "-X github.com/csaf-poc/csaf_distribution/v3/util.SemVersion=v3.0.0-rc.1-5-gf572a3b" -v ./cmd/...
internal/options/log.go:12:2: package log/slog is not in GOROOT (/usr/local/go/src/log/slog)
make: *** [Makefile:78: build_linux] Error 1
```

If I remember correctly, the `slog` was also a reason why we choose Go 1.21... Or is that an error on my side?

2023-11-16 07:18 UTC, juan131 commented
@tschmidtb51 I think slog was already in Go 1.20 as experimental, see https://pkg.go.dev/golang.org/x/exp/slog
but I'll give it a try and let you know

2023-11-16 07:33 UTC, juan131 commented
I could reproduce the issue with this simple Dockerfile @tschmidtb51:

```Dockerfile
FROM bitnami/golang:1.20.11 as builder
COPY . /csaf_distribution
WORKDIR /csaf_distribution
RUN mkdir /output && \
    go build -o /output -ldflags "-X github.com/csaf-poc/csaf_distribution/v3/util.SemVersion=v3.0.0-rc.1-5-gf572a3b" -v ./cmd/...

FROM bitnami/bitnami-shell
COPY --from=builder /output /app
WORKDIR /app
ENTRYPOINT ["/app/csaf_checker"]
```

```console
$ docker build . -t csaf-distro-image
(...)
11.09 internal/options/log.go:12:2: package log/slog is not in GOROOT (/opt/bitnami/go/src/log/slog)
```

I guess this overcomplicates maintaining compatibility with 1.20 significantly. Should we at least create a `go-1.20` branch as suggested by @mpermar and replace `slog` there?

2023-11-16 07:47 UTC, juan131 commented
I could reproduce the issue with this simple Dockerfile @tschmidtb51:

```Dockerfile
FROM bitnami/golang:1.20.11 as builder
COPY . /csaf_distribution
WORKDIR /csaf_distribution
RUN mkdir /output && \
    go build -o /output -ldflags "-X github.com/csaf-poc/csaf_distribution/v3/util.SemVersion=v3.0.0-rc.1-5-gf572a3b" -v ./cmd/...

FROM bitnami/bitnami-shell
COPY --from=builder /output /app
WORKDIR /app
ENTRYPOINT ["/app/csaf_checker"]
```

```console
$ docker build . -t csaf-distro-image
(...)
11.09 internal/options/log.go:12:2: package log/slog is not in GOROOT (/opt/bitnami/go/src/log/slog)
```

I guess this overcomplicates maintaining compatibility with 1.20 significantly. Should we at least create a `go-1.20` branch as suggested by @mpermar and replace `slog` there?

2023-11-16 07:52 UTC, s-l-teichmann commented
> Did someone test that successfully?
> 
> I just tried to run in on a machine with Go 1.20.4 and got the following result:
> 
> ```
> make build_linux 
> mkdir -p bin-linux-amd64/ 
> env GOARCH=amd64 GOOS=linux go build -o bin-linux-amd64/  -ldflags "-X github.com/csaf-poc/csaf_distribution/v3/util.SemVersion=v3.0.0-rc.1-5-gf572a3b" -v ./cmd/...
> internal/options/log.go:12:2: package log/slog is not in GOROOT (/usr/local/go/src/log/slog)
> make: *** [Makefile:78: build_linux] Error 1
> ```
> 
> If I remember correctly, the `slog` was also a reason why we choose Go 1.21... Or is that an error on my side?

@tschmidt Yes, you are right. I totally forgot this. My bad.

2023-11-19 02:46 UTC, tschmidtb51 commented
> > We also need to change the workflows to make sure that we are not accidentally using 1.21 functions...
> 
> @tschmidtb51 No, we should _not_ do this. We should always use the latest stable to build our stuff. The `go.mod` file ensures that we don't use language features of a higher version. The binaries we deliver should benefit from the newer compilers.

@s-l-teichmann: You mentioned that we shouldn't build with go 1.20 but those file changes (in the Github Actions) seem still to be part of the PR. Was that intentional?

2023-11-23 15:13 UTC, juan131 commented
any update on this? Thanks in advance

2023-11-23 17:11 UTC, tschmidtb51 commented
We have discussed the path forward:
- A new, cleaned up PR will be created.
- The policy will be to support the latest stable and the oldstable go version.
- For the meantime (until the next Go release, 2024-02), we accept the risk that comes from the experimental libraries (as long as nothing breaks).
- If something breaks, we'll need to reevaluate.

2023-11-24 12:40 UTC, s-l-teichmann commented
Replacesd by PR #514

2023-11-24 12:40 UTC, closed without merging