Added support for structured logging in `csaf_aggretator`
csaf-poc/csaf_distribution pull request #530
Opened 2024-04-18 17:53 UTC by oxisto

This PR adds structured logging for the aggregator service. Currently, only the text handler is used, but I can extend this to use the JSON handler as well. In this case, probably some code that is shared between the aggregator and the downloader would need to be moved to a common package.

I was also wondering, whether this repo is moving to Go 1.21 at the future, since `slog` was introduced in to the standard lib in 1.21. So currently, this still relies on the `x/exp` package.

Fixes #462

2024-04-18 20:38 UTC, s-l-teichmann commented
Thank for your contribution. I will review the PR as soon as I've git some time.

> I was also wondering, whether this repo is moving to Go 1.21 at the future, since `slog` was introduced in to the standard lib in 1.21. So currently, this still relies on the `x/exp` package.

We clearly can do this as we already where there. The 'x/exp' stuff was only introduced in PR #514 to help backwards compatibility.

2024-04-18 20:47 UTC, oxisto commented
> Thank for your contribution. I will review the PR as soon as I've git some time.

Looking forward to the feedback!

> 
> > I was also wondering, whether this repo is moving to Go 1.21 at the future, since `slog` was introduced in to the standard lib in 1.21. So currently, this still relies on the `x/exp` package.
> 
> We clearly can do this as we already where there. The 'x/exp' stuff was only introduced in PR #514 to help backwards compatibility.

Ah I see. Well it should be more or less a case of just replacing the exp package with the `slog` package, once you decide to revisit Go 1.21.

2024-04-19 16:55 UTC, tschmidtb51 commented
Just a reminder: When we update the Go version, this also needs to be documented in https://github.com/csaf-poc/csaf_distribution/blob/main/README.md#build-from-sources and https://github.com/csaf-poc/csaf_distribution/blob/main/docs/Development.md#supported-go-versions as well.

2024-04-23 12:37 UTC, bernhardreiter commented
@oxisto are you okay with the new license `Apache-2.0` for your contribution #535 ?

Can you also do the Go Version update has part of this PR?

2024-04-23 13:16 UTC, oxisto commented
> @oxisto are you okay with the new license `Apache-2.0` for your contribution #535 ?

Yes, that is ok for me.

> 
> Can you also do the Go Version update has part of this PR?

Sure, I can do that and already use `slog` instead of the x/exp one.

2024-04-23 18:42 UTC, bernhard-herzog reviewed
I tested this briefly and it seems to work. I didn't check all the changed log statements, though.

2024-04-24 11:06 UTC, bernhardreiter commented
@oxisto a side question about Github: Is it possible for your to run the "Integration Test" workflow (https://github.com/oxisto/csaf_distribution/blob/main/.github/workflows/itest.yml ) because obviously I cannot do this on your clone and as it is not part of our automatic test I have not figured out how to run it on a pull request manually).

2024-04-24 15:22 UTC, bernhardreiter commented
@oxisto in one commit message you are asking a few questions (which ideally shouldn't be in a commit message):

> but I can extend this to use the JSON handler as well. 

It should be similar to how the downloader handels it.

> In this case, probably some code that is shared between the aggregator 
> and the downloader would need to be moved to a common package.

Yes common code should go into a common package, we already have util.

Both can be done in different PRs.

2024-04-24 15:41 UTC, bernhardreiter commented on cmd/csaf_aggregator/mirror.go
> +	w.log.Debug("Creating symbol", "from", w.dir, "to", target)
should be "sym link" instead of "symbol"

2024-04-24 15:47 UTC, bernhardreiter requested changes
LGTM and works.
A symbolic link is called `symbol` twice, I recommend to change this.

Removing the `verbose` command line option and adding setting for the log-level would be the next step, however it might also affect the command line, so it can be delayed.

2024-04-24 15:50 UTC, oxisto commented
> @oxisto in one commit message you are asking a few questions (which ideally shouldn't be in a commit message):
> 
> > but I can extend this to use the JSON handler as well.
> 
> It should be similar to how the downloader handels it.
> 
> > In this case, probably some code that is shared between the aggregator
> > and the downloader would need to be moved to a common package.
> 
> Yes common code should go into a common package, we already have util.
> 
> Both can be done in different PRs.

Sure, once this is merged I can have a look at what can be extracted into a common package, so that other tools can potentially use this as well and that behaviour is consistent across `cmd`.

Apart from that I have changed the symbol to sym link.

2024-04-24 18:43 UTC, oxisto commented
> @oxisto a side question about Github: Is it possible for your to run the "Integration Test" workflow (https://github.com/oxisto/csaf_distribution/blob/main/.github/workflows/itest.yml ) because obviously I cannot do this on your clone and as it is not part of our automatic test I have not figured out how to run it on a pull request manually).

https://github.com/oxisto/csaf_distribution/actions/runs/8821657205/job/24218013269

2024-04-24 19:44 UTC, bernhardreiter approved these changes
works and LGTM

2024-04-25 10:39 UTC, bernhard-herzog approved these changes
Looks good to me now

2024-04-25 11:13 UTC, merged