docs: fix licensing info for generated files
csaf-poc/csaf_distribution pull request #542
Opened 2024-05-03 16:04 UTC by bernhardreiter

* change generate_cvss_enums.go to note that the input file is relevant for the license.
 * change license and copyright of cvss20enums.go and cvss3enums.go to BSD-3-Clause and FIRST.
 * add reuse.software 3.0 compatible files for the schema cvss files.

resolves #534

2024-05-08 06:03 UTC, JanHoefelmeyer approved these changes
LGTM & works

2024-05-10 19:56 UTC, tschmidtb51 commented
I might have missed that. Why is it assumed to be BSD-3clause?

2024-05-13 09:34 UTC, bernhardreiter commented
> I might have missed that. Why is it assumed to be BSD-3clause?

The input files are licensed under `BSD-3-Clause`  by FIRST, e.g. see
https://github.com/csaf-poc/csaf_distribution/blob/main/csaf/schema/cvss-v2.0.json#L2-L21

And see comment in the improved generate_cvss_enums.go:
```go
// We from Intevation consider the source code parts in the following
// template file as too insignificant to be a piece of work that gains
// "copyrights" protection in the European Union. So the license(s)
// of the output files are fully determined by the input file.
```

2024-06-20 08:27 UTC, bernhardreiter commented
@s-l-teichmann ping

2024-06-20 10:15 UTC, s-l-teichmann requested changes
This is not correctly used.

Running `go generate ./...` in root folder results in a diff
```
diff --git a/csaf/cvss20enums.go b/csaf/cvss20enums.go
index 97d2e10..d7c647d 100644
--- a/csaf/cvss20enums.go
+++ b/csaf/cvss20enums.go
@@ -1,5 +1,4 @@
-// SPDX-License-Identifier: BSD-3-Clause
-// SPDX-FileCopyrightText: 2017 FIRST.ORG, INC.
+// determine license(s) from input file and replace this line
 //
 // THIS FILE IS MACHINE GENERATED. EDIT WITH CARE!
 
diff --git a/csaf/cvss3enums.go b/csaf/cvss3enums.go
index 32e01e3..1367820 100644
--- a/csaf/cvss3enums.go
+++ b/csaf/cvss3enums.go
@@ -1,5 +1,4 @@
-// SPDX-License-Identifier: BSD-3-Clause
-// SPDX-FileCopyrightText: 2017 FIRST.ORG, INC.
+// determine license(s) from input file and replace this line
 //
 // THIS FILE IS MACHINE GENERATED. EDIT WITH CARE!
```

There should be no diff!

2024-06-21 06:11 UTC, s-l-teichmann approved these changes

2024-06-21 06:21 UTC, JanHoefelmeyer approved these changes
No longer a diff

LGTM & works

2024-06-21 12:02 UTC, merged