Extend unit test coverage in util
csaf-poc/csaf_distribution pull request #545
Opened 2024-06-12 08:18 UTC by koplas

This is the first batch of new tests that expand the test coverage in the `util` package. Later pull requests will address the unit tests for the `casf` package.

2024-06-20 09:59 UTC, JanHoefelmeyer approved these changes
Significant improvement in coverage, couldn't find any mistakes:
LGTM & works

2024-06-21 11:57 UTC, s-l-teichmann requested changes
LGTM (with remarks)

2024-06-21 11:57 UTC, s-l-teichmann commented on util/csv_test.go
> +		if err != nil {
`if err := csvWriter.Write(x); err != nil {` here. Same on other places, too.

2024-06-21 11:57 UTC, s-l-teichmann commented on util/file_test.go
> +	doc := make(map[string]interface{})
Please use `any` instead of `interface{}`. Same below

2024-06-21 11:57 UTC, s-l-teichmann commented on util/file_test.go
> +	os.MkdirAll(filepath.Join(dir, "src/folder0"), 0755)
Add error handling.

2024-06-24 11:09 UTC, s-l-teichmann approved these changes

2024-06-24 12:44 UTC, JanHoefelmeyer approved these changes
LGTM & works

2024-06-24 12:48 UTC, merged