feat: no longer require to be root user to call setup scripts
csaf-poc/csaf_distribution pull request #552
Opened 2024-07-24 05:19 UTC by JanHoefelmeyer

Currently you need to be root to use the setupscripts as described. This will allow users with sudo privileges to use the setup scripts as well.

2024-07-30 07:51 UTC, bernhardreiter approved these changes
LGTM

2024-07-30 07:54 UTC, koplas approved these changes

2024-07-30 14:31 UTC, koplas requested changes

2024-07-30 14:31 UTC, koplas commented on docs/scripts/Readme.md
Running `source ./TLSConfigsForITest.sh` will result in user logout. Multiple runs of `TLSConfigsForITest.sh` will result in a broken nginx configuration.

2024-07-31 07:09 UTC, bernhardreiter commented
> Multiple runs of TLSConfigsForITest.sh will result in a broken nginx configuration.

That is known and accepted for now, as this are just helpers. So it is not subject to improvement in this merge request. You could add a hint to the readme though.

2024-08-01 09:17 UTC, cintek reviewed
LGTM & works

2024-08-01 09:19 UTC, cintek approved these changes

2024-08-05 06:41 UTC, koplas commented on docs/scripts/Readme.md
If a single command in the script fails, it will logout the user. This makes debugging more difficult.

2024-08-05 10:18 UTC, bernhardreiter commented on docs/scripts/Readme.md
@koplas it is a known situation that if a single command fails with "source" and this bash mode, but better than to not fail.

2024-08-05 11:03 UTC, koplas approved these changes
I still prefer a failsafe, but this can be handled in another pull request.

2024-08-05 14:41 UTC, merged