Use a default user agent
csaf-poc/csaf_distribution pull request #553
Opened 2024-07-25 11:45 UTC by koplas

Closes #500

2024-07-31 07:16 UTC, bernhardreiter commented on util/client.go
> +		req.Header.Add("User-Agent", "csaf-distribution "+SemVersion)
The generated user agent must follow https://datatracker.ietf.org/doc/html/rfc9110#name-user-agent which it currently does not.

2024-07-31 07:17 UTC, bernhardreiter requested changes
* Documentation changes are missing.
* The chosen user-agent does not seem standard compliant (see comment).

2024-08-05 05:24 UTC, JanHoefelmeyer approved these changes
LGTM

2024-08-05 14:48 UTC, bernhardreiter approved these changes
LGTM
@JanHoefelmeyer can you also do a functional test, please.

2024-08-08 07:24 UTC, JanHoefelmeyer commented
Have done a functional test, so LGTM & works

2024-08-08 07:24 UTC, JanHoefelmeyer approved these changes

2024-08-09 12:28 UTC, merged