Fix(Setup Scripts): add sudo to commands that would fail due to missing permissions when running as nonroot user
csaf-poc/csaf_distribution pull request #557
Opened 2024-08-08 09:48 UTC by JanHoefelmeyer

https://github.com/csaf-poc/csaf_distribution/pull/552 is not working properly. The scripts no longer fail, but a lot of the test setup isn't set up properly due to missing permissions.  This should fix it.

2024-09-09 14:27 UTC, cintek approved these changes
LGTM & works

2024-09-12 15:49 UTC, bernhardreiter requested changes
There does not seem to be a change that actually changes a permission problem, all writes go into a user's directory. So it does not look like a good solution. Can you explain more precisely which failure you are trying to fix?

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/TLSClientConfigsForITest.sh
> +'  | sudo tee ~/${FOLDERNAME}/clientCertificateConfigs.txt
This sudo should not be necessary as ~/${FOLDERNAME} is in the user's directory.

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/TLSConfigsForITest.sh
> +'  | sudo tee ~/${FOLDERNAME}/TLSConfigs.txt
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/TLSConfigsForITest.sh
> +'  | sudo tee ~/${FOLDERNAME}/TLS8443Configs.txt
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +sudo mkdir -p ~/${FOLDERNAME}
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +sudo certtool --generate-privkey --outfile testclient1-key.pem
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +'  | sudo tee gnutls-certtool.testclient1.template
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +sudo certtool --generate-certificate --load-privkey testclient1-key.pem --outfile testclient1.crt --load-ca-certificate rootca-cert.pem --load-ca-privkey rootca-key.pem --template gnutls-certtool.tes
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +sudo certtool --load-ca-certificate rootca-cert.pem --load-certificate testclient1.crt --load-privkey testclient1-key.pem --to-p12 --p12-name "Test Client 1" --null-password --outder --outfile testcl
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +sudo certtool --generate-privkey --outfile testclient2-key.pem
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +' | sudo tee gnutls-certtool.testclient2.template
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +sudo certtool --generate-certificate --load-privkey testclient2-key.pem --outfile testclient2.crt --load-ca-certificate rootca-cert.pem --load-ca-privkey rootca-key.pem --template gnutls-certtool.tes
Should not be necessary (see above).

2024-09-12 15:49 UTC, bernhardreiter commented on docs/scripts/createCCForITest.sh
> +sudo certtool --load-ca-certificate rootca-cert.pem --load-certificate testclient2.crt --load-privkey testclient2-key.pem --to-p12 --p12-name "Test Client 2" --null-password --outder --outfile testcl
Should not be necessary (see above).

2024-09-26 08:43 UTC, JanHoefelmeyer commented
While I was pretty sure that I had problems with permissions before, you are right that I can't reproduce them even on main right now. Thus this may not be necessary.

2024-09-26 08:43 UTC, closed without merging