Improve PGP fingerprint handling
csaf-poc/csaf_distribution pull request #558
Opened 2024-08-08 10:25 UTC by koplas

Warn if no fingerprint is specified and give more details if fingerprint comparison fails.

2024-08-08 10:32 UTC, s-l-teichmann requested changes

2024-08-08 10:32 UTC, s-l-teichmann commented on cmd/csaf_checker/processor.go
> +			p.badPGPs.error("Given Fingerprint ('%q') of public OpenPGP key %q does not match remotely loaded ('%q').", string(key.Fingerprint), u, ckey.GetFingerprint())
`s/'%q'/%q/g`

2024-08-09 15:02 UTC, tschmidtb51 commented
Is the case "no fingerprint is given for this key" differentiated from "an empty fingerprint is given for this key"?

2024-08-10 19:57 UTC, koplas commented
> Is the case "no fingerprint is given for this key" differentiated from "an empty fingerprint is given for this key"?

No, in this implementation, both cases are handled the same. To separate both cases, `csaf.PGPKey` needs to be changed, which affects the public API.

2024-08-12 08:15 UTC, tschmidtb51 commented
> > Is the case "no fingerprint is given for this key" differentiated from "an empty fingerprint is given for this key"?
> 
> No, in this implementation, both cases are handled the same. To separate both cases, `csaf.PGPKey` needs to be changed, which affects the public API.

In future versions, we should differentiate that. 
@bernhardreiter / @s-l-teichmann: Please decide when it makes most sense to implemented this.

2024-09-04 15:04 UTC, bernhardreiter commented
> > Is the case "no fingerprint is given for this key" differentiated from "an empty fingerprint is given for this key"?

> To separate both cases, `csaf.PGPKey` needs to be changed, which affects the public API.

Then we should not implement it for 3.x as we would need to go to version 4 if we change the public API. @koplas can you implement a version that just gives more details for 3.x? (Please do not put in unrelated whitespace changes.)

@tschmidtb51 wrote:
> In future versions, we should differentiate that.

If I understand the schema correctly there is a ` "minLength": 40` in place. So I'd expect an empty fingerprint value would violate the schema. So I expect both cases to result into to different messages. @koplas can you test what happens with an empty fingerprint value in the current code?

2024-09-04 15:08 UTC, bernhardreiter commented
(@s-l-teichmann sorry for the back and forth of your review. It has been addressed and I am trying to remove you as a requested reviewer, which somehow does not work.)

2024-09-06 15:57 UTC, koplas commented
> If I understand the schema correctly there is a ` "minLength": 40` in place. So I'd expect an empty fingerprint value would violate the schema. So I expect both cases to result into to different messages. @koplas can you test what happens with an empty fingerprint value in the current code?

If the fingerprint is empty, the `csaf_checker` prints the following error message: "Could not parse the Provider-Metadata.json".
Using the `csaf_downloader` will result in "no valid provider-metadata.json found".
No additional error messages are printed with this branch and the schema validation prevents the check for empty fingerprints.

2024-09-07 07:23 UTC, bernhardreiter commented
As discussed in #555 we won't be using this approach.

2024-09-07 07:23 UTC, closed without merging